import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  analyzeThirdPartyRisks, THIRD_PARTY_RULES_VERSION, type FileEntry,
} from '../src/index.ts';

const root = await fs.mkdtemp(path.join(os.tmpdir(), 'codesucker-third-party-'));

async function write(relPath: string, text: string): Promise<FileEntry> {
  const absolute = path.join(root, relPath);
  await fs.mkdir(path.dirname(absolute), { recursive: true });
  await fs.writeFile(absolute, text, 'utf8');
  const stat = await fs.stat(absolute);
  const ext = path.extname(relPath).slice(1);
  return {
    path: absolute, relPath, name: path.basename(relPath), ext, lang: ext.toUpperCase(),
    sizeBytes: stat.size, rawLines: text.split(/\r\n|\r|\n/).length,
    mtimeMs: stat.mtimeMs, encoding: 'UTF-8', included: true, entryScore: 0,
  };
}

try {
  await fs.writeFile(path.join(root, 'package.json'), JSON.stringify({
    name: 'self-app', dependencies: {
      'left-pad': '^1.3.0', '@self/local': 'workspace:*', '/Users/private/customer': '^1.0.0',
    },
  }));
  await fs.writeFile(path.join(root, 'pom.xml'), `
    <project><artifactId>self-java</artifactId><dependencies><dependency>
      <groupId>org.apache.commons</groupId><artifactId>commons-lang3</artifactId>
    </dependency></dependencies></project>
  `);
  await fs.writeFile(path.join(root, 'go.mod'), `
    module example.local/self
    require github.com/acme/tool v1.2.3
    require example.local/internal v0.0.0
    replace example.local/internal => ./internal
  `);
  await fs.writeFile(path.join(root, 'Cargo.toml'), `
    [package]
    name = "self-rust"
    [dependencies]
    serde = "1"
    local-crate = { path = "crates/local" }
  `);
  await fs.writeFile(path.join(root, 'requirements.txt'), 'requests==2.32.0\n-e ./local-python\n');
  await fs.mkdir(path.join(root, 'broken'), { recursive: true });
  await fs.writeFile(path.join(root, 'broken/pom.xml'), '<!DOCTYPE foo><project></project>');

  const files = await Promise.all([
    write('vendor/left-pad/index.js', '// SPDX-License-Identifier: MIT\nmodule.exports = value => value;'),
    write('external/commons-lang3/StringUtils.java', 'class StringUtils {}'),
    write('third_party/github.com/acme/tool/tool.go', 'package tool'),
    write('deps/serde/lib.rs', 'pub fn serialize() {}'),
    write('vendors/requests/api.py', 'def get(): pass'),
    write('vendor/local/src.ts', 'export const local = true;'),
    write('src/client.generated.ts', '// Code generated by self; DO NOT EDIT.\nexport const value = 1;'),
    write('src/string-only.ts', 'const sample = "Code generated by demo; DO NOT EDIT";\nconst author = "Copyright Mallory";'),
    write('src/owned.ts', '// Copyright 2026 Example Team\nexport const owned = true;'),
  ]);

  const originalFetch = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error('network access is forbidden in third-party analysis'); };
  const first = await analyzeThirdPartyRisks(root, files);
  const second = await analyzeThirdPartyRisks(root, [...files].reverse());
  globalThis.fetch = originalFetch;

  assert.equal(first.rulesVersion, THIRD_PARTY_RULES_VERSION);
  assert.ok(first.summary.analyzedManifests >= 5, '五类生态清单都应参与离线分析');
  assert.deepEqual(first.findings.map((finding) => finding.id), second.findings.map((finding) => finding.id), '输入顺序不应改变稳定 finding ID');
  assert.ok(first.diagnostics.some((item) => item.code === 'manifest-parse-failed' && item.file === 'broken/pom.xml'));

  const dependencyFiles = new Set(first.findings
    .filter((finding) => finding.kind === 'dependency-source')
    .flatMap((finding) => finding.affected.relPaths));
  for (const relPath of [
    'vendor/left-pad/index.js', 'external/commons-lang3/StringUtils.java',
    'third_party/github.com/acme/tool/tool.go', 'deps/serde/lib.rs', 'vendors/requests/api.py',
  ]) {
    assert.ok(dependencyFiles.has(relPath), `${relPath} 应由本地清单与目录映射为依赖源码`);
  }
  assert.ok(!dependencyFiles.has('vendor/local/src.ts'), 'workspace/local/path 依赖不能默认判为第三方依赖源码');
  assert.ok(first.findings.some((finding) => finding.kind === 'vendored-source' && finding.affected.relPaths.includes('vendor/local/src.ts')),
    '无法映射的 vendor 目录只能给出中置信提示');
  assert.ok(first.findings.some((finding) => finding.kind === 'license-declaration' && finding.affected.relPaths.includes('vendor/left-pad/index.js')));
  assert.ok(first.findings.some((finding) => finding.kind === 'generated-source' && finding.affected.relPaths.includes('src/client.generated.ts')));
  assert.ok(first.findings.some((finding) => finding.kind === 'attribution-declaration' && finding.affected.relPaths.includes('src/owned.ts')));
  assert.ok(!first.findings.some((finding) => finding.affected.relPaths.includes('src/string-only.ts')),
    '字符串中的生成/署名示例不能形成风险发现');

  const serialized = JSON.stringify(first);
  assert.ok(!serialized.includes(root), '报告不得包含项目绝对路径');
  assert.ok(!serialized.includes('/Users/private/customer'), '非法依赖名称不得把绝对路径带入报告');
  assert.ok(!serialized.includes('module.exports = value'), '报告不得包含源码正文');
  assert.ok(!serialized.includes('Copyright Mallory'), '报告不得包含字符串或原始署名行');
  assert.equal(first.summary.findingCount, first.findings.length);
  assert.equal(first.summary.affectedFileCount, new Set(first.findings.flatMap((finding) => finding.affected.relPaths)).size);

  console.log('✅ third-party-risk 全部通过');
} finally {
  await fs.rm(root, { recursive: true, force: true });
}
